<?php

namespace Tests\Codeception\Task\Extension;

use Codeception\Event\FailEvent;
use Codeception\Task\Extension\FailedTestsReporter;
use PHPUnit\Framework\TestCase;
use SplFileInfo;
use Symfony\Component\Finder\Finder;

/**
 * Class FailedTestsReporterTest
 * @coversDefaultClass \Codeception\Task\Extension\FailedTestsReporter
 */
class FailedTestsReporterTest extends TestCase
{
    private $failedTests = [
        ['testname' => 'tests/acceptance/bar/baz.php:testA',],
        ['testname' => 'tests/acceptance/bar/baz.php:testB',],
        ['testname' => 'tests/acceptance/bar/baz.php:testC',],
        ['testname' => 'tests/acceptance/bar/baz.php:testD',],
        ['testname' => 'tests/acceptance/bar/baz.php:testE',],
        ['testname' => 'tests/acceptance/bar/baz.php:testF',],
        ['testname' => 'tests/acceptance/bar/baz.php:testG',],
        ['testname' => 'tests/acceptance/bar/baz.php:testH',],
    ];

    /**
     * @covers ::endRun
     */
    public function testEndRun(): void
    {
        $reporter = $this->getMockBuilder(FailedTestsReporter::class)
            ->disableOriginalConstructor()
            ->onlyMethods(['getTestname', 'getLogDir'])
            ->getMock();

        $reporter->method('getLogDir')->willReturn(TEST_PATH . '/result/');

        // prepare Mocks for Test
        $testEvents = [];
        foreach ($this->failedTests as $test) {
            $eventMock = $this->getMockBuilder(FailEvent::class)
                ->disableOriginalConstructor()
                ->getMock();

            $testEvents[] = [
                'mock' => $eventMock,
                'testname' => $test['testname']
            ];
        }

        // get Testname by the TestEventMock
        $reporter
            ->method('getTestname')
            ->withConsecutive(
                ...array_map(
                    static function (FailEvent $event): array {
                        return [$event];
                    },
                    array_column($testEvents, 'mock')
                )
            )
            ->willReturnOnConsecutiveCalls(...array_column($testEvents, 'testname'));

        foreach ($testEvents as $event) {
            $reporter->afterFail($event['mock']);
        }

        $reporter->endRun();
        $files = Finder::create()
            ->followLinks()
            ->files()
            ->in(TEST_PATH)
            ->path('result')
            ->name('/^failedTests_\w+\.\w+\.txt$/');

        $iterator = $files->getIterator();
        $this->assertCount(1, $iterator);
        $iterator->rewind();
        /** @var SplFileInfo $file */
        $file = $iterator->current();
        $this->assertTrue($file->isFile());
        $content = explode(PHP_EOL, file_get_contents($file->getPathname()));
        $this->assertCount(8, $content);
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $files = Finder::create()
            ->followLinks()
            ->files()
            ->in(TEST_PATH)
            ->path('result')
            ->name('/^failedTests_\w+\.\w+\.txt$/');

        foreach ($files->getIterator() as $file) {
            unlink($file->getPathname());
        }
    }
}
